### ISSUE TITLE
Creating node module along with brower based utility

### ISSUE THREAD

**Issue by ketanghumatkar** [flexmonster/pivot-xml-report-converter#1]
Can we convert this browser level utiltiy to nodejs module? This can have few advantages

1. Command line utility which will convert xml file to json file that I can later save to database as flexmonster configuration
2. Brower level utility convert xml manually one by one which is blocker in automatically converting all xml to json through any script

**Comment by flexmonster** [comment]
Hello Ketan,

Thank you for the feedback.
It sounds reasonable. We will take a look how to convert the code to Npm module and keep supporting browser version as well. Does it work for you?

**Comment by flexmonster** [comment]
Hello Ketan,
The npm module for the node.js is available now, please check the Readme file in the repository.
You are welcome to try it.
Regards,
The Flexmonster team.
